### ISSUE TITLE
Colorado PAL

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#151]
Check out the Frying Pan out of Basalt, CO. Again, only using this as an example to hopefully uncover the datasets that would apply to the rest of the state. I've been there within the last 6 months and there is some missing public land/access between Basalt and the reservoir. Check out this old map that suggests where is public/private by CPW. Haven't looking into parcel info but probably some new PAL to add in here. 

https://cpw.state.co.us/thingstodo/Fishery%20Survey%20Summaries/FryingpanRiver.pdf

**Comment by andest01** [comment]
@zacharyrpope I'd be curious if this shows up in PADUS. I'll go and check.
`localhost:3000/co/grand-junction`

![image](https://user-images.githubusercontent.com/1424223/45981625-56efb480-c01b-11e8-993d-30bda785c299.png)

**Comment by andest01** [comment]
@zacharyrpope after reviewing PADUS, I suspect the area you're referring to is in GREEN. Please confirm.

![image](https://user-images.githubusercontent.com/1424223/45984403-8e179300-c026-11e8-9630-40a77ee1dd18.png)

Looks like there's a lot of good stuff in Colorado's "CPW Public Access Properties" shapefile.
 https://www.arcgis.com/home/item.html?id=b1b27dc4bde744e490e0d1a9f9512032

However, it looks like there's a lot of properties that may not be open for fishing - specifically hunting only.

![image](https://user-images.githubusercontent.com/1424223/45985323-55c68380-c02b-11e8-8fe8-f67392becd8b.png)

Furthermore, some of these areas are _not_ held whatsoever in the most recent PADUS data set. Note the splotches of blue, where there only should be BLACK or RED. This is mildly disconcerting.
![image](https://user-images.githubusercontent.com/1424223/45985429-d2596200-c02b-11e8-8914-e6beffbdb621.png)

In order to proceed with Colorado, I'll have to learn what the following items mean in the context of Colorado:

- [ ] Conservation Pool
- [ ] Hunting Access (Non-STL)
- [ ] SAA
- [ ] SFU
- [ ] SHA
- [ ]  SP
- [ ] STL
- [ ] SWA
- [ ] WWA
- [ ] Recreation Area

Remember, the _raison d'etre_ for the app is
> Help anglers make *safe and legal* choices when fishing for trout.

Because of this, I am much more permissive of false negatives (public being mislabeled private) than the horrible situation of the false positive (getting shot).

@zacharyrpope please confirm that we're at least on the right track with the public land on the Frying Pan. If so, then I'll move forward on improving Colorado, which is an extremely high-value target because of water access rights.

**Comment by ghost** [comment]
@andest01 It looks like you're screenshots have it covered perfectly. There are specific pull-outs not far up-stream from Basalt that I had in mind. These are places that I have fished and have been given recommendations from local guides, definitely public in these particular areas. Just wanted you to be aware of it in case it uncovered new datasets to consider. Nice work!

**Comment by andest01** [comment]
https://cpw.state.co.us/Documents/RulesRegs/Brochure/lands.pdf

## SWA: State Wildlife Area 
https://web.archive.org/web/20140110084832/http://wildlife.state.co.us/landwater/statewildlifeareas/pages/swa.aspx

![image](https://user-images.githubusercontent.com/1424223/50618371-e4af2b80-0eb7-11e9-9052-d00bc0ebad75.png)


State wildlife areas (SWAs) are state- or privately-owned lands that offer
state-managed, wildlife-related recreation to the public.
 While most activities focus on hunting and fishing, each SWA has
different allowed activities based on location and available resources. These
parcels of SWA land are paid for by sportsmen and sportswomen, and
managed under state law by Colorado Parks and Wildlife employees for the
benefit of wildlife. CPW manages about 350 SWA lands around the state.
 Read on for information about each SWA, pages 4−28, and get ready
to plan your next adventure. Look online for SWA maps: cpw.state.
co.us/WildlifeAreaMaps

## SP: State Park
![image](https://user-images.githubusercontent.com/1424223/50618400-1627f700-0eb8-11e9-9849-e004f7ff30c2.png)
Seems pretty legit. Seems like you can fish em whenever.

![image](https://user-images.githubusercontent.com/1424223/50618511-e9281400-0eb8-11e9-9837-53381b5c53ae.png)


![image](https://user-images.githubusercontent.com/1424223/50618514-f2b17c00-0eb8-11e9-9d3e-f83d39f4ff32.png)


## STL: State Trust Lands
![image](https://user-images.githubusercontent.com/1424223/50618427-3f488780-0eb8-11e9-8691-b278ac4df46c.png)
Can I fish 'em? Sorta. Can I fish 'em whenever I like? No. They're only open from time to time.

![image](https://user-images.githubusercontent.com/1424223/50618457-774fca80-0eb8-11e9-8648-802aa7074836.png)

![image](https://user-images.githubusercontent.com/1424223/50618471-89ca0400-0eb8-11e9-8d37-d3d8434edd3b.png)

**Comment by andest01** [comment]
SWAs are a no from me. There are too many one-off restrictions on both activity and time span.
![image](https://user-images.githubusercontent.com/1424223/50618719-6011dc80-0eba-11e9-8082-815edc48b60f.png)

**Comment by zpope0803** [comment]
Seems like a reasonable justification to me, nice research.

**Comment by andest01** [comment]
I've pushed this one as far as I'm comfortable with.
