### ISSUE TITLE
Eastern Wisconsin - seasonal runs

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#155]
Just curious, is the scope here exclusive to native stream trout and not lake trout/salmon runs? Eastern Wisconsin can be pretty ridiculous (in a good way) in the fall with the lake runs. Is the thought not to include that use case? Used to live in Milwaukee and enjoyed the fall season out there along the coast...

**Comment by andest01** [comment]
If I understand you correctly, you're pointing to the fact that the Eastern half of Wisconsin has meager trout stream representation, and the fall/spring runs are significant enough to warrant consideration of their introduction into the TroutSpotr database. Is this a fair summary?

![image](https://user-images.githubusercontent.com/1424223/46094060-98e53b80-c17e-11e8-90c2-fa6d2afa881e.png)

TroutSpotr is built almost exclusively from US _state_ data. So in this case, I'm posting what Wisconsin has told me are its trout streams. I'd rather not get into the business of curating individual streams. If the state says this is a trout stream, then I'll catalog it. This is how MN, WI, and IA have been built (with the exception of "trap streams" - streams that watermark my data and [help pinpoint copycats](https://en.wikipedia.org/wiki/Trap_street)).

The wide exception was using NORWeST data to cover areas where state governments simply _don't bother cataloging trout streams_ cuz they're all in the hills anyways. These are places like Montana, Colorado, and Idaho, though I think Idaho might actually have a regulations data set, which would then imply trout streams.

Lakes are another bridge I don't want to cross. Lakes could _easily_ be visualized, not unlike publicly accessible land, but cataloging their use and regulations are... a new kettle of fish. Also, then people will want _all_ lakes to be cataloged, which will push the payload size of each region well beyond the 600 kb compressed limit for smart phones. They'll also ask, "What about Smallmouth Bass?"

Once I spread my concentration too thin, and try to make it all things to all people, the app gets _worse._ This I believe: the moment an app starts to expand its use beyond a simple one-line thesis marks the moment the app begins to suck.

Don't let this post harsh the vibe. If you can find a data set of those streams, along with their regulations, then we can consider adding them to the database -- but understand that the blue line is a symbol of trust between the user and TroutSpotr. Trust is something that's gained in drops, and lost in buckets. If these streams are either dry or too warm in the summer, that rightfully damages the reputation of the data. Introducing false positives into the database is something to be avoided. Adding more verbiage to say "maybe you'll like this stream, but only at these specific times of the year" pushes the app towards wikipedia style editorializing, rather than a strict facts-first approach. It also adds a surprising amount of app-logic.

Every feature I make, and every feature I say no to, has to pass the filter:
Does this feature help or harm the purpose of the app:
> Help anglers find safe and legal opportunities when fishing for trout.

I'm going to create a new tag: data required. If you can produce trustworthy data, then I'll consider adding it - this would include lakes.

**Comment by ghost** [comment]
Well said. I wasn't suggesting it should considered into the database, just asking if it was intended to be already (hence warranting a bug report). I couldn't agree more with doing a few things well, rather than many things mediocre or lousy. I'd suggest keeping to the current TS scope/charter and let folks like me make my own "river run" database as needed. This would take on a world of its own if you start looking at the coasts or even the larger scope of the great lakes, just a different beast altogether.

**Comment by andest01** [comment]
Ok, I'll close this ticket; working as designed.
