### ISSUE TITLE
Stream quality indicators

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#162]
This issue/inquiry is on the underlying data, as opposed to the web interface.

In the folder, static/data/v3, there is the concept of a stream layer, which is embedded in the topo .lyr file. Within the stream layer, there are fields that suggest or refer to trout quality of that river. Specifically, there are flags for whether brown/brook/raindow trout are present and/or stocked. 

Is there a document that describes how these flags were derived? How reliable are these flags in the database? Some streams suggest no presence or stocking of any trout, wondering if the underlying logic behind these flags are reliable. 

Thanks!
-Zach

**Comment by andest01** [comment]
Eh, they sort of were used back when MN had these on record. This was back in the early days. I don't have any data for WI or IA.

The data was pulled manually from a spreadsheet that I made. Nothing should be trusted.

![image](https://user-images.githubusercontent.com/1424223/46917961-e856a480-cf91-11e8-8bb3-02d99ddef90d.png)




# Here's a file. Rename .txt to .tsv because its tab separated.
[StreamSpeciesBlank - StreamSpecies v1.txt](https://github.com/troutspotr/troutspotr-frontend/files/2476488/StreamSpeciesBlank.-.StreamSpecies.v1.txt)

**Comment by zpope0803** [comment]
Ah makes sense, thats kind of what I figured. Thanks for the info!
