### ISSUE TITLE
MN - Tax forfeited land

### ISSUE THREAD

**Issue by zpope0803** [troutspotr/troutspotr-frontend#166]
https://www.stlouiscountymn.gov/departments-a-z/land-minerals/tax-forfeited-trust-lands/tax-forfeiture: "Tax forfeited lands, for the most part, are open to the public for hunting, fishing, hiking, camping and other forms of dispersed recreation (all federal, state and local laws and regulations apply)."

Opens up a lot of land on the North Shore...

**Comment by andest01** [comment]
Ah, this one. This isn't the first time I've had someone ask about exactly this case, in precisely the same county. It's just as interesting now as it was a year ago when my lawyer reviewed this idea.

## Trespassing Issues
Yes, it does open up _a lot_ of land, but the problem is that even though it's the State's land, you can still trespass on State property, as carefully noted in the quote's "for the most part" qualification. This becomes a tricky detail.

## Scaling Issues
This land is notoriously ephemeral - money and land change hands quickly. You'd have to keep your data sets up to the week to keep your clients safe. It would be a real scaling issue.

## Ethical Issues
I showed my council a GIS image of all the TF land between Duluth and Two Harbors. There was a lot of red in that map. He grabbed his chest in pain. I was like, "what's the big deal?". He said, "That's a sign of a dying city."

I get this image in my head:

I think of someone's grandma's old homestead with a big red sheet of paper stapled to the front door and the remains of an untended garden out back. Maybe an old swing set idly shifting in the breeze. Now I think of an angler dressed in head to toe with over three grand worth of gear. I just don't think it's a good look.

I mean, _I wouldn't_ do it, but it's always up to the person who's doing it. Who knows.

Maybe it's not grandma's land. Maybe it's a mining company that went belly up, or some other corporation. Either way, to my mind it's a wound to the community that lives there.

For these reasons, I'm not comfortable with acquiring and distributing TF land.

## Opportunity
It's very possible to write a script that pulls this data in and processes it every day, or maybe week. Now do it for all Counties (no State-level data!) and do that for all States. It's a bridge too far for me, but it's something that would set anyone else apart.

Also, getting City Parks would be a pretty big benefit to anyone living in or near Duluth, MN.

**Comment by zpope0803** [comment]
Interesting thoughts, thanks for the insight!

**Comment by andest01** [comment]
For posterity, for anyone who's looking, this is an image of the Tax Forfeiture land:
![image](https://user-images.githubusercontent.com/1424223/49826086-a6f13400-fd4b-11e8-87c1-d1aacfd854bc.png)

**Comment by zpope0803** [comment]
I think I might have different data than you. Where is yours from? I was using:
https://gisdata.mn.gov/dataset/plan-stateland-dnrcounty

Also, good point about city parks. How do we get these added? Below is a list of parks I've checked and confirmed aren't on TS.

Mill Creek Park, Chatfield, MN
Hartley Park, Duluth, MN
Chester Park, Duluth, MN
Bagley Natural Area, Duluth, MN
Enger Park, Duluth, MN
Lincoln Park, Duluth MN
Fritz Loven Park, Lake Shore, MN (Stoney Brook Creek)

**Comment by zpope0803** [comment]
I agree with Stu on the tax-forfeited land. I may continue to evaluate specific parcels that are strategic value, but not as part of TS. 

Regarding Park's listed above, and related to issue #150, I think the only real way to get this data is parcel-level data which is rarely available at the state level. Doing so at the county level is incredibly tedious and often times not super reliable. Back to the 80/20 rule.
