### ISSUE TITLE
MN - state_other_lands

### ISSUE THREAD

**Issue by zpope0803** [troutspotr/troutspotr-frontend#167]
https://gisdata.mn.gov/dataset/bdry-state-forest

The specific layer, "state_forest_other_lands" isn't included in TS. The example below adds a fair amount of public water on East Beaver Creek. Is the reason the layer description below?

"State Forests - Other Forest Lands
This theme shows State Forest lands outside of the State Forest Statutory Boundaries. It was derived from MNDNR's Land Records System PLS40 data layer. Sub-40 shapes are not represented. Partial PLS40 ownership is represented as a whole PLS40. _This data is not survey quality and should never be used to resolve land ownership disputes_. "

![screen shot 2018-12-11 at 1 43 05 pm](https://user-images.githubusercontent.com/41308309/49825864-1286d180-fd4b-11e8-8ba8-0ce6f907f11c.png)

**Comment by zpope0803** [comment]
Looks legit from the DNR maps.

![screen shot 2018-12-11 at 1 48 57 pm](https://user-images.githubusercontent.com/41308309/49826126-bec8b800-fd4b-11e8-89dc-eb4c7bc4d476.png)

**Comment by andest01** [comment]
how did i miss this post?

I shied away from this one because of the PLS(S) 40 name, which I do not trust. There's good news to be found in this post, though, so keep reading.

For those of you watching from home, `PLSS 40` refers to a standard surveying unit that seems to be pretty, well, standard in the United States of America.

Ever wonder why Iowa looks like this:
![image](https://user-images.githubusercontent.com/1424223/50050063-d5a63c00-00b6-11e9-9b99-d8594ff32ce6.png)


Or where the (unfortunate) phrase "40 acres and a mule" came from?

This is from the PLSS name:
https://en.wikipedia.org/wiki/Section_(United_States_land_surveying)


Anyways, there's an awful lot of geo-spatial data out there that isn't high resolution, and is instead bound to the resolution of 40 acres (!!). Instead of telling you _where_ things are, they'd just tell you _which_ PLSS you could find it in. That's like stepping down from a 4K PC monitor, to an 8-bit NES and an eye cataract.

So you can imagine why I would be rather uninterested in that level of "resolution". _But it sounds like you're saying these areas are actually literally entirely a PLSS 40 section, rather than some smaller percentage thereof._ Is that right?

If so, I'd be very interested in acquiring this data. let me know if I understand this situation correctly.

**Comment by zpope0803** [comment]
Hmm interesting background and context, I didn't know that! 

That could very well be the case. I guess the real question would be for the DNR. They published the North Shore trout streams with those "PLS40" blocks as easements/public land. Maybe its worth an email to them confirming whether or not its actually public?

**Comment by andest01** [comment]
I do actually recall talking with a Point of Contact in Rochester about PLS40, and somebody else who worked in the Duluth-area DNR. They were both rather leary of using PLS40 as a basis of a map. "But why is it in the DNR's maps then?" I asked.

🤷‍♂️ was the answer.


ftp://ftp.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_dnr/bdry_state_forest/metadata/metadata.html
> State Forests - Other Forest Lands
> This theme shows State Forest lands outside of the State Forest Statutory Boundaries. It was derived from MNDNR's Land Records System PLS40 data layer. Sub-40 shapes are not represented. Partial PLS40 ownership is represented as a whole PLS40. This data is not survey quality and should never be used to resolve land ownership disputes. 

However, I remember seeing a (mythical) layer that noted the "percentage" of land cover inside a PLS 40 that was considered state land...

But for what it's worth, there are some definite false positives in the "other lands" layer. Check this out:
![image](https://user-images.githubusercontent.com/1424223/50057715-c1545480-0133-11e9-9878-2105106c28f8.png)

To my eye, that looks very private. :(
